name: Build commit

on:
  - push
  - workflow_dispatch

env:
  RELEASE: true

jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          tools: composer:v2
        env:
          fail-fast: true

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-node-and-composer-${{ hashFiles('**/package-lock.json', '**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-and-composer-

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm ci
          composer update

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Lint
        run: |
          composer run-script csfixer

      - name: Build
        run: task

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: WiiDatabase-Toolkit-${{ github.SHA }}.zip
          path: build/*
          if-no-files-found: error
          retention-days: 90
